# Generated by Django 6.0 on 2026-01-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('football', 'Nogomet'), ('basketball', 'Košarka'), ('tennis', 'Tenis'), ('volleyball', 'Odbojka'), ('handball', 'Rukomet'), ('baseball', 'Bejzbol')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='⚽', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sportovi',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField()),
                ('description', models.TextField()),
                ('is_popular', models.BooleanField(default=False)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='pages.sportchoice')),
            ],
            options={
                'verbose_name': 'Formacija',
                'verbose_name_plural': 'Formacije',
                'ordering': ['sport', '-is_popular', 'total_players'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.formation')),
            ],
            options={
                'verbose_name': 'Tim',
                'verbose_name_plural': 'Timovi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pages.team')),
            ],
            options={
                'verbose_name': 'Igrač',
                'verbose_name_plural': 'Igrači',
                'ordering': ['team', 'order'],
            },
        ),
    ]
