# Generated by Django 6.0 on 2026-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sportchoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sportchoice',
            name='icon',
        ),
        migrations.AlterField(
            model_name='sportchoice',
            name='name',
            field=models.CharField(choices=[('football', 'Nogomet'), ('basketball', 'Košarka'), ('tennis', 'Tenis'), ('volleyball', 'Odbojka'), ('handball', 'Rukomet')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
