# Generated by Django 6.0.3 on 2026-06-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_team_formation_remove_player_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Tim',
                'verbose_name_plural': 'Timovi',
                'ordering': ['generation', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('players_per_team', models.PositiveSmallIntegerField()),
                ('has_goalkeeper', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='pages.sportchoice')),
            ],
            options={
                'verbose_name': 'Formacija',
                'verbose_name_plural': 'Formacije',
                'ordering': ['sport', '-is_popular', 'players_per_team'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_goalkeeper', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pages.generatedteam')),
            ],
            options={
                'verbose_name': 'Igrač',
                'verbose_name_plural': 'Igrači',
                'ordering': ['team', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeamGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalkeepers', models.JSONField(blank=True, default=list)),
                ('field_players', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='pages.formation')),
            ],
            options={
                'verbose_name': 'Generiranje timova',
                'verbose_name_plural': 'Generiranja timova',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedteam',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pages.teamgeneration'),
        ),
    ]
